- name: Remove the galaxy credential requirement for roles and collections
  hosts: localhost
  vars:
    tasks_path: /var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/tasks.py
  tasks:
    - name: Patch roles
      ansible.builtin.replace:
        path: "{{ tasks_path }}"
        regexp: 'galaxy_creds_are_defined and settings.AWX_ROLES_ENABLED'
        replace: 'settings.AWX_ROLES_ENABLED'

    - name: Patch collections
      ansible.builtin.replace:
        path: "{{ tasks_path }}"
        regexp: 'galaxy_creds_are_defined and settings.AWX_COLLECTIONS_ENABLED'
        replace: 'settings.AWX_COLLECTIONS_ENABLED'
